steps:
  count: 30
  delay: 1000

hotel:
  elevator:
    capacity: 3
  spawn-probability:
    ground: 0.65
    other: 0.35
  display:
    column-width:
      floor: 7
      elevator: 3
      persons: 20
